# -*- coding: utf-8 -*-
"""CLOA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12H5-NpTtrN21fBkCC_swino-w5sXWvpQ
"""

import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import (
    accuracy_score, precision_score, recall_score, f1_score,
    roc_auc_score, confusion_matrix, matthews_corrcoef, cohen_kappa_score
)

from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier, GradientBoostingClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from xgboost import XGBClassifier

df = pd.read_csv("/content/stroke_risk_dataset.csv")

X = df.drop(columns=["At Risk (Binary)", "Stroke Risk (%)"])
y = df["At Risk (Binary)"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42, stratify=y
)

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

models = {
    "Logistic Regression": LogisticRegression(max_iter=2000),
    "SVM": SVC(probability=True),
    "KNN": KNeighborsClassifier(),
    "Decision Tree": DecisionTreeClassifier(),
    "Random Forest": RandomForestClassifier(),
    "AdaBoost": AdaBoostClassifier(),
    "Gradient Boosting": GradientBoostingClassifier(),
    "Naive Bayes": GaussianNB(),
    "LDA": LinearDiscriminantAnalysis(),
    "XGBoost": XGBClassifier(use_label_encoder=False, eval_metric="logloss")
}

results = []

for name, model in models.items():
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    y_prob = model.predict_proba(X_test)[:, 1]

    tn, fp, fn, tp = confusion_matrix(y_test, y_pred).ravel()

    results.append({
        "Model": name,
        "Accuracy": accuracy_score(y_test, y_pred),
        "Precision": precision_score(y_test, y_pred),
        "Recall (Sensitivity)": recall_score(y_test, y_pred),
        "F1-Score": f1_score(y_test, y_pred),
        "ROC-AUC": roc_auc_score(y_test, y_prob),
        "Specificity": tn / (tn + fp),
        "MCC": matthews_corrcoef(y_test, y_pred),
        "Kappa": cohen_kappa_score(y_test, y_pred)
    })

results_df = pd.DataFrame(results)
results_df = results_df.sort_values(by="Accuracy", ascending=False)
print(results_df)

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import (
    accuracy_score, precision_score, recall_score, f1_score,
    roc_auc_score, confusion_matrix,
    matthews_corrcoef, cohen_kappa_score
)

from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier, GradientBoostingClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from xgboost import XGBClassifier

df = pd.read_csv("/content/stroke_risk_dataset.csv")

X = df.drop(columns=["At Risk (Binary)", "Stroke Risk (%)"])
y = df["At Risk (Binary)"]

feature_names = X.columns.tolist()
n_features = len(feature_names)

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42, stratify=y
)

population_size = 20
max_iter = 30
beta = 0.5
np.random.seed(42)

population = np.random.randint(0, 2, (population_size, n_features))

def fitness(mask):
    if mask.sum() == 0:
        return 0
    model = LogisticRegression(max_iter=2000)
    model.fit(X_train.iloc[:, mask == 1], y_train)
    preds = model.predict(X_test.iloc[:, mask == 1])
    return accuracy_score(y_test, preds)

fitness_vals = np.array([fitness(ind) for ind in population])
best_solution = population[np.argmax(fitness_vals)]

for _ in range(max_iter):
    for i in range(population_size):
        r = np.random.rand()
        if r < beta:
            new_sol = population[i] + np.random.randint(-1, 2, n_features)
        else:
            new_sol = population[i] + np.random.rand() * (best_solution - population[i])

        new_sol = (1 / (1 + np.exp(-new_sol)) > 0.5).astype(int)
        new_fit = fitness(new_sol)

        if new_fit > fitness_vals[i]:
            population[i] = new_sol
            fitness_vals[i] = new_fit

    best_solution = population[np.argmax(fitness_vals)]

selected_features = [feature_names[i] for i in range(n_features) if best_solution[i] == 1]

print("CLOA Selected Features:")
print(selected_features)

X_train_fs = X_train[selected_features]
X_test_fs = X_test[selected_features]

scaler = StandardScaler()
X_train_fs = scaler.fit_transform(X_train_fs)
X_test_fs = scaler.transform(X_test_fs)

rf = RandomForestClassifier(n_estimators=200, random_state=42)
rf.fit(X_train_fs, y_train)

importance_df = pd.DataFrame({
    "Feature": selected_features,
    "Importance Score": rf.feature_importances_
}).sort_values(by="Importance Score", ascending=False)

print("\nFeature Ranking after CLOA:")
print(importance_df)

# Plot
plt.figure(figsize=(8, 5))
plt.barh(importance_df["Feature"], importance_df["Importance Score"])
plt.xlabel("Importance Score")
plt.ylabel("Feature")
plt.title("Feature Importance after CLOA Feature Selection")
plt.gca().invert_yaxis()
plt.tight_layout()
plt.show()

models = {
    "Logistic Regression": LogisticRegression(max_iter=2000),
    "SVM": SVC(probability=True),
    "KNN": KNeighborsClassifier(),
    "Decision Tree": DecisionTreeClassifier(),
    "Random Forest": RandomForestClassifier(),
    "AdaBoost": AdaBoostClassifier(),
    "Gradient Boosting": GradientBoostingClassifier(),
    "Naive Bayes": GaussianNB(),
    "LDA": LinearDiscriminantAnalysis(),
    "XGBoost": XGBClassifier(use_label_encoder=False, eval_metric="logloss")
}

def evaluate_models(Xtr, Xte, title):
    results = []

    for name, model in models.items():
        model.fit(Xtr, y_train)
        y_pred = model.predict(Xte)
        y_prob = model.predict_proba(Xte)[:, 1]

        tn, fp, fn, tp = confusion_matrix(y_test, y_pred).ravel()

        results.append({
            "Model": name,
            "Accuracy": accuracy_score(y_test, y_pred),
            "Precision": precision_score(y_test, y_pred),
            "Recall": recall_score(y_test, y_pred),
            "F1-Score": f1_score(y_test, y_pred),
            "ROC-AUC": roc_auc_score(y_test, y_prob),
            "Specificity": tn / (tn + fp),
            "MCC": matthews_corrcoef(y_test, y_pred),
            "Kappa": cohen_kappa_score(y_test, y_pred)
        })

    df_results = pd.DataFrame(results).sort_values(by="Accuracy", ascending=False)
    print(f"\n{title}")
    print(df_results)
    return df_results

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

results_without_fs = evaluate_models(
    X_train_scaled, X_test_scaled,
    "Results WITHOUT Feature Selection"
)

results_with_fs = evaluate_models(
    X_train_fs, X_test_fs,
    "Results WITH CLOA Feature Selection"
)

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import (
    accuracy_score, precision_score, recall_score, f1_score,
    roc_auc_score, confusion_matrix,
    matthews_corrcoef, cohen_kappa_score
)

from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier, GradientBoostingClassifier
from sklearn.naive_bayes import GaussianNB

df = pd.read_csv("/content/stroke_risk_dataset.csv")

X = df.drop(columns=["At Risk (Binary)", "Stroke Risk (%)"])
y = df["At Risk (Binary)"]

feature_names = X.columns.tolist()
n_features = len(feature_names)

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42, stratify=y
)

population_size = 20
max_iter = 25
beta = 0.5
np.random.seed(42)

population = np.random.randint(0, 2, (population_size, n_features))

def fitness(mask):
    if mask.sum() != 8:   # 🔴 force exactly 8 features
        return 0
    model = LogisticRegression(max_iter=2000)
    model.fit(X_train.iloc[:, mask == 1], y_train)
    preds = model.predict(X_test.iloc[:, mask == 1])
    return accuracy_score(y_test, preds)

fitness_vals = np.array([fitness(ind) for ind in population])
best_solution = population[np.argmax(fitness_vals)]

for _ in range(max_iter):
    for i in range(population_size):
        r = np.random.rand()

        if r < beta:
            new_sol = population[i] + np.random.randint(-1, 2, n_features)
        else:
            new_sol = population[i] + np.random.rand() * (best_solution - population[i])

        new_sol = (1 / (1 + np.exp(-new_sol)) > 0.5).astype(int)

        if new_sol.sum() != 8:
            continue

        new_fit = fitness(new_sol)
        if new_fit > fitness_vals[i]:
            population[i] = new_sol
            fitness_vals[i] = new_fit

    best_solution = population[np.argmax(fitness_vals)]

selected_features = [feature_names[i] for i in range(n_features) if best_solution[i] == 1]

print("✅ CLOA Selected 8 Features:")
print(selected_features)

X_train_fs = X_train[selected_features]
X_test_fs = X_test[selected_features]

scaler = StandardScaler()
X_train_fs = scaler.fit_transform(X_train_fs)
X_test_fs = scaler.transform(X_test_fs)

rf = RandomForestClassifier(n_estimators=200, random_state=42)
rf.fit(X_train_fs, y_train)

importance_df = pd.DataFrame({
    "Feature": selected_features,
    "Importance Score": rf.feature_importances_
}).sort_values(by="Importance Score", ascending=False)

print("\n📊 Feature Importance Scores:")
print(importance_df)

# Plot
plt.figure(figsize=(8, 5))
plt.barh(importance_df["Feature"], importance_df["Importance Score"])
plt.xlabel("Importance Score")
plt.title("Feature Importance after CLOA (8 Features)")
plt.gca().invert_yaxis()
plt.tight_layout()
plt.show()

models = {
    "Logistic Regression": LogisticRegression(max_iter=2000),
    "SVM": SVC(probability=True),
    "KNN": KNeighborsClassifier(),
    "Decision Tree": DecisionTreeClassifier(),
    "Random Forest": RandomForestClassifier(),
    "AdaBoost": AdaBoostClassifier(),
    "Gradient Boosting": GradientBoostingClassifier(),
    "Naive Bayes": GaussianNB()
}

results = []

for name, model in models.items():
    model.fit(X_train_fs, y_train)
    y_pred = model.predict(X_test_fs)
    y_prob = model.predict_proba(X_test_fs)[:, 1]

    tn, fp, fn, tp = confusion_matrix(y_test, y_pred).ravel()

    results.append({
        "Model": name,
        "Accuracy": accuracy_score(y_test, y_pred),
        "Precision": precision_score(y_test, y_pred),
        "Recall": recall_score(y_test, y_pred),
        "F1-Score": f1_score(y_test, y_pred),
        "ROC-AUC": roc_auc_score(y_test, y_prob),
        "Specificity": tn / (tn + fp),
        "MCC": matthews_corrcoef(y_test, y_pred),
        "Kappa": cohen_kappa_score(y_test, y_pred)
    })

results_df = pd.DataFrame(results).sort_values(by="Accuracy", ascending=False)
print("\n📈 Model Performance using CLOA Selected Features:")
print(results_df)

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import (
    accuracy_score, precision_score, recall_score, f1_score,
    roc_auc_score, confusion_matrix,
    matthews_corrcoef, cohen_kappa_score
)

from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier, GradientBoostingClassifier
from sklearn.naive_bayes import GaussianNB

df = pd.read_csv("/content/stroke_risk_dataset.csv")

X = df.drop(columns=["At Risk (Binary)", "Stroke Risk (%)"])
y = df["At Risk (Binary)"]

feature_names = X.columns.tolist()
n_features = len(feature_names)

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42, stratify=y
)

population_size = 20
max_iter = 25
beta = 0.5
np.random.seed(42)

population = np.random.randint(0, 2, (population_size, n_features))

def fitness(mask):
    if mask.sum() != 8:
        return 0
    model = LogisticRegression(max_iter=2000)
    model.fit(X_train.iloc[:, mask == 1], y_train)
    preds = model.predict(X_test.iloc[:, mask == 1])
    return accuracy_score(y_test, preds)

fitness_vals = np.array([fitness(ind) for ind in population])
best_solution = population[np.argmax(fitness_vals)]

for _ in range(max_iter):
    for i in range(population_size):
        r = np.random.rand()
        if r < beta:
            new_sol = population[i] + np.random.randint(-1, 2, n_features)
        else:
            new_sol = population[i] + np.random.rand() * (best_solution - population[i])

        new_sol = (1 / (1 + np.exp(-new_sol)) > 0.5).astype(int)
        if new_sol.sum() != 8:
            continue

        new_fit = fitness(new_sol)
        if new_fit > fitness_vals[i]:
            population[i] = new_sol
            fitness_vals[i] = new_fit

    best_solution = population[np.argmax(fitness_vals)]

selected_features = [feature_names[i] for i in range(n_features) if best_solution[i] == 1]

print("✅ CLOA Selected Features:", selected_features)

scaler_full = StandardScaler()
X_train_full = scaler_full.fit_transform(X_train)
X_test_full = scaler_full.transform(X_test)

X_train_fs = X_train[selected_features]
X_test_fs = X_test[selected_features]

scaler_fs = StandardScaler()
X_train_fs = scaler_fs.fit_transform(X_train_fs)
X_test_fs = scaler_fs.transform(X_test_fs)

models = {
    "Logistic Regression": LogisticRegression(max_iter=2000),
    "SVM": SVC(probability=True),
    "KNN": KNeighborsClassifier(),
    "Decision Tree": DecisionTreeClassifier(),
    "Random Forest": RandomForestClassifier(),
    "AdaBoost": AdaBoostClassifier(),
    "Gradient Boosting": GradientBoostingClassifier(),
    "Naive Bayes": GaussianNB()
}

def evaluate(Xtr, Xte, title):
    results = []

    for name, model in models.items():
        model.fit(Xtr, y_train)
        y_pred = model.predict(Xte)
        y_prob = model.predict_proba(Xte)[:, 1]

        tn, fp, fn, tp = confusion_matrix(y_test, y_pred).ravel()

        results.append({
            "Model": name,
            "Accuracy": accuracy_score(y_test, y_pred),
            "Precision": precision_score(y_test, y_pred),
            "Recall": recall_score(y_test, y_pred),
            "F1-Score": f1_score(y_test, y_pred),
            "ROC-AUC": roc_auc_score(y_test, y_prob),
            "Specificity": tn / (tn + fp),
            "MCC": matthews_corrcoef(y_test, y_pred),
            "Kappa": cohen_kappa_score(y_test, y_pred)
        })

    df_results = pd.DataFrame(results).sort_values(by="Accuracy", ascending=False)
    print(f"\n📊 {title}")
    print(df_results)
    return df_results

results_without_fs = evaluate(
    X_train_full, X_test_full,
    "Results WITHOUT Feature Selection"
)

results_with_fs = evaluate(
    X_train_fs, X_test_fs,
    "Results WITH CLOA Feature Selection"
)

import matplotlib.pyplot as plt

# Feature names and normalized scores
features = [
    "Age",
    "Pain in Neck/Jaw/Shoulder/Back",
    "Irregular Heartbeat",
    "Swelling (Edema)",
    "Nausea / Vomiting",
    "Chest Discomfort (Activity)",
    "Shortness of Breath",
    "Anxiety / Feeling of Doom"
]

scores = [0.6864, 0.0456, 0.0453, 0.0453, 0.0448, 0.0445, 0.0441, 0.0441]

# Figure size
fig_width, fig_height = 6, 4
plt.figure(figsize=(fig_width, fig_height))

# Dynamic font scaling based on figure size
base_font = fig_width * 1.5   # automatic scaling

# Horizontal bar plot
bars = plt.barh(
    features,
    scores,
    color="green",
    edgecolor="black"
)

# Invert y-axis
plt.gca().invert_yaxis()

# Add value labels (bold & dark)
for bar in bars:
    width = bar.get_width()
    plt.text(
        width + 0.005,
        bar.get_y() + bar.get_height() / 2,
        f"{width:.3f}",
        va="center",
        fontsize=base_font,
        fontweight="bold",
        color="black"
    )

# Axis labels (bold & dark)
plt.xlabel(
    "Normalized Feature Importance Score",
    fontsize=base_font + 1,
    fontweight="bold",
    color="black"
)

plt.ylabel(
    "Selected Features",
    fontsize=base_font + 1,
    fontweight="bold",
    color="black"
)

# Make tick labels bold & dark
plt.xticks(fontsize=base_font, fontweight="bold", color="black")
plt.yticks(fontsize=base_font, fontweight="bold", color="black")

# Tight layout
plt.tight_layout()

# Save high-resolution figure
plt.savefig(
    "Stroke_Feature_Importance_Top8.png",
    dpi=300,
    bbox_inches="tight"
)

plt.show()

import numpy as np
import matplotlib.pyplot as plt

# Metrics
metrics = [
    "Accuracy", "Precision", "Recall", "F1-Score",
    "ROC-AUC", "Specificity", "MCC", "Kappa"
]

# Values (percentage)
without_fs = [98.23, 98.19, 98.46, 98.33, 99.48, 97.56, 96.41, 96.41]
with_fs    = [99.66, 99.61, 99.86, 99.74, 99.99, 99.28, 99.25, 99.25]

x = np.arange(len(metrics))
width = 0.35

plt.figure(figsize=(13, 6))

bars1 = plt.bar(x - width/2, without_fs, width, label="Without Feature Selection")
bars2 = plt.bar(x + width/2, with_fs, width, label="With Feature Selection")

# Value labels (BOLD)
for bar in bars1:
    plt.text(
        bar.get_x() + bar.get_width()/2,
        bar.get_height() + 0.12,
        f"{bar.get_height():.2f}",
        ha="center",
        fontsize=10,
        fontweight="bold"
    )

for bar in bars2:
    plt.text(
        bar.get_x() + bar.get_width()/2,
        bar.get_height() + 0.12,
        f"{bar.get_height():.2f}",
        ha="center",
        fontsize=10,
        fontweight="bold"
    )

# Axis labels and ticks (BOLD)
plt.xticks(x, metrics, rotation=30, fontsize=11, fontweight="bold")
plt.yticks(fontsize=11, fontweight="bold")
plt.ylabel("Score (%)", fontsize=12, fontweight="bold")
plt.xlabel("Evaluation Metrics", fontsize=12, fontweight="bold")

# Title (BOLD)
plt.title(
    "Performance Comparison With and Without Feature Selection",
    fontsize=14,
    fontweight="bold"
)

plt.ylim(90, 101)

# Legend (BOLD, moved outside)
legend = plt.legend(
    loc="upper left",
    bbox_to_anchor=(1.01, 1),
    prop={"weight": "bold", "size": 11}
)

plt.grid(axis="y", linestyle="--", alpha=0.6)
plt.tight_layout()
plt.show()

import numpy as np
import matplotlib.pyplot as plt

# Metrics
metrics = [
    "Accuracy", "Precision", "Recall", "F1-Score",
    "ROC-AUC", "Specificity", "MCC", "Kappa"
]

# Values (percentage)
without_fs = [98.23, 98.19, 98.46, 98.33, 99.48, 97.56, 96.41, 96.41]
with_fs    = [99.66, 99.61, 99.86, 99.74, 99.99, 99.28, 99.25, 99.25]

x = np.arange(len(metrics))
width = 0.35

plt.figure(figsize=(10, 5))

# 🔹 BAR COLORS + OUTLINE COLORS
bars1 = plt.bar(
    x - width/2,
    without_fs,
    width,
    label="Without Feature Selection",
    color="#4C72B0",        # blue fill
    edgecolor="black",      # outline
    linewidth=1.5
)

bars2 = plt.bar(
    x + width/2,
    with_fs,
    width,
    label="With Feature Selection",
    color="#DD8452",        # orange fill
    edgecolor="black",      # outline
    linewidth=1.5
)

# Value labels (BOLD)
for bar in bars1:
    plt.text(bar.get_x() + bar.get_width()/2,
             bar.get_height() + 0.12,
             f"{bar.get_height():.2f}",
             ha="center", fontsize=8, fontweight="bold")

for bar in bars2:
    plt.text(bar.get_x() + bar.get_width()/2,
             bar.get_height() + 0.12,
             f"{bar.get_height():.2f}",
             ha="center", fontsize=8, fontweight="bold")

# Axis labels and ticks (BOLD)
plt.xticks(x, metrics, rotation=30, fontsize=11, fontweight="bold")
plt.yticks(fontsize=11, fontweight="bold")
plt.ylabel("Score (%)", fontsize=12, fontweight="bold")
plt.xlabel("Evaluation Metrics", fontsize=12, fontweight="bold")

# Title (BOLD)
plt.title(
    "Performance Comparison With and Without Feature Selection",
    fontsize=14,
    fontweight="bold"
)

plt.ylim(90, 101)

# Legend (BOLD, outside)
plt.legend(
    loc="upper left",
    bbox_to_anchor=(1, 1),
    prop={"weight": "bold", "size": 5}
)

plt.grid(axis="y", linestyle="--", alpha=0.6)
plt.tight_layout()
plt.tight_layout()

# Save high-resolution figure
plt.savefig(
    "aa.png",
    dpi=300,
    bbox_inches="tight")
plt.show()

import pandas as pd
import matplotlib.pyplot as plt
from imblearn.combine import SMOTEENN

# Load dataset
df = pd.read_csv('/content/stroke_risk_dataset.csv')

# ---------------- BEFORE BALANCING ----------------
counts_before = df['At Risk (Binary)'].value_counts()

plt.figure(dpi=300)
counts_before.plot(
    kind='bar',
    color=['#e74c3c', '#3498db']
)
plt.xlabel('Class Label', fontsize=12)
plt.ylabel('Number of Samples', fontsize=12)
plt.title('Class Distribution Before Balancing', fontsize=14)
plt.xticks(rotation=0)
plt.tight_layout()
plt.show()
# Save high-resolution figure
plt.savefig(
    "a1.png",
    dpi=300,
    bbox_inches="tight")
plt.show()

# ---------------- APPLY BALANCING ----------------
X = df.drop(columns=['At Risk (Binary)'])
y = df['At Risk (Binary)']

# New / Hybrid Balancing Technique
smote_enn = SMOTEENN(random_state=42)
X_bal, y_bal = smote_enn.fit_resample(X, y)

# ---------------- AFTER BALANCING ----------------
counts_after = y_bal.value_counts()

plt.figure(dpi=300)
counts_after.plot(
    kind='bar',
    color=['#2ecc71', '#9b59b6']
)
plt.xlabel('Class Label', fontsize=12)
plt.ylabel('Number of Samples', fontsize=12)
plt.title('Class Distribution After SMOTEENN Balancing', fontsize=14)
plt.xticks(rotation=0)
plt.tight_layout()
plt.show()
# Save high-resolution figure
plt.savefig(
    "a2.png",
    dpi=300,
    bbox_inches="tight")
plt.show()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.utils.class_weight import compute_class_weight

# Load dataset
df = pd.read_csv('/content/stroke_risk_dataset.csv')

X = df.drop(columns=['At Risk (Binary)'])
y = df['At Risk (Binary)']

# ---------------- CLASS DISTRIBUTION ----------------
counts = y.value_counts()

plt.figure(dpi=300)
counts.plot(kind='bar', color=['#ff6b6b', '#4dabf7'])
plt.xlabel('Class Label', fontsize=12)
plt.ylabel('Number of Samples', fontsize=12)
plt.title('Original Class Distribution (Imbalanced)', fontsize=14)
plt.xticks(rotation=0)
plt.tight_layout()
plt.show()
plt.savefig(
    "a1.png",
    dpi=300,
    bbox_inches="tight")
plt.show()
# ---------------- WEIGHTED FOCAL BALANCING ----------------
# Compute class weights
classes = np.unique(y)
class_weights = compute_class_weight(
    class_weight='balanced',
    classes=classes,
    y=y
)

class_weight_dict = {
    classes[i]: class_weights[i] for i in range(len(classes))
}

print("Class Weights:", class_weight_dict)
plt.savefig(
    "a2.png",
    dpi=300,
    bbox_inches="tight")
plt.show()